### ISSUE TITLE
Yaml parser dies on document separator within a literal multiline string

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_k8s#116]
This yaml fails to parse due to the `---` within in the literal block multiline string:

This seems to be a common pattern "in the wild".

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: present-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: name: present_mapping
      prefix: /present/
      service: present-svc
spec:
  type: ClusterIP
  selector:
    app: present-app
  ports:
  - port: 80
    name: http-present
    targetPort: http-api
```

```sh
$ bazel run //k8s:present-bad.apply
INFO: Running command line: bazel-bin/k8s/present-bad.apply
Traceback (most recent call last):
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 205, in <module>
    main()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 191, in main
    for x in inputs.split(_DOCUMENT_DELIMITER)
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 82, in Resolve
    return yaml.dump(walk(yaml.load(input)))
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<string>", line 3, column 17:
          name: name: present_mapping
                    ^
error: no objects passed to apply
```

The workaround is to use a traditional string (which represents yaml in literal JSON form).

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: present-svc
  annotations:
    getambassador.io/config: '{ "apiVersion": "ambassador/v0", "kind": "Mapping", "name": "present_mapping", "prefix": "/present/", "service": "present-svc" }'
spec:
  type: ClusterIP
  selector:
    app: present-app
  ports:
  - port: 80
    name: http-present
    targetPort: http-api
```

**Comment by mattmoor** [comment]
For this particular example we could change things to split on: `^---\n`, but IIUC for this to be perfectly correct it needs to be integrated with the `yaml` parser itself.

I probably didn't spend enough time looking for alternatives, since `PyYAML` seems to support a `load_all` function for this...

I think we need to change [this](https://github.com/bazelbuild/rules_k8s/blob/master/k8s/resolver.py#L82) but I need to get ready and catch a shuttle right now :)

**Comment by pcj** [comment]
Whoops there was another issue in that original yaml `name: name: ...`.  Here's the actual error:

```
Traceback (most recent call last):
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 205, in <module>
    main()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 191, in main
    for x in inputs.split(_DOCUMENT_DELIMITER)
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/__main__/../io_bazel_rules_k8s/k8s/resolver.py", line 82, in Resolve
    return yaml.dump(walk(yaml.load(input)))
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/pcj/.cache/bazel/_bazel_pcj/0d0e0af9cfe4eeaa94b6061a6dc2c16e/execroot/__main__/bazel-out/k8-fastbuild/bin/k8s/present-bad.apply.runfiles/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "<string>", line 6, column 1:
    spec:
    ^
error: no objects passed to apply
```
