### ISSUE TITLE
key "config" not found in dictionary

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_k8s#142]
Following the example: https://github.com/bazelbuild/rules_k8s/pull/8/files#diff-04c6e90faac2675aa89e2176d2eec7d8R79

I get the following error any ideas?

ERROR
```
ERROR: /workspace/src/github.com/legalweb/cosmicapis/deployments/identities/BUILD:5:1: in _k8s_object rule //deployments/identities:dev:
Traceback (most recent call last):
        File "/workspace/src/github.com/legalweb/cosmicapis/deployments/identities/BUILD", line 5
                _k8s_object(name = 'dev')
        File "/private/var/tmp/_bazel_bweston/7c5537f8cb3a288e50f11aeb5e04b824/external/io_bazel_rules_k8s/k8s/object.bzl", line 83, in _impl
                _runfiles(ctx, image["config"])
        File "/private/var/tmp/_bazel_bweston/7c5537f8cb3a288e50f11aeb5e04b824/external/io_bazel_rules_k8s/k8s/object.bzl", line 83, in _runfiles
                image["config"]
key "config" not found in dictionary
```

WORKSPACE file
```

git_repository(
  name = "io_bazel_rules_k8s",
  commit = "8537afcc8728e5ebfafa9b68462e54a98935d06b",
  remote = "https://github.com/bazelbuild/rules_k8s.git",
)
```

BUILD file
```
package(default_visibility = ["//visibility:public"])

load("@k8s_deploy//:defaults.bzl", "k8s_deploy")

k8s_deploy(
  name = "dev",
  template = ":deployment.yaml",
  images = {
    "gcr.io/cosmic-1106/identities/api-server:staging": "//src/cosmicapis/identities/cmd/identities-api-server:image",
    "gcr.io/cosmic-1106/identities/http-gateway:staging": "//src/cosmicapis/identities/cmd/identities-http-gateway:image",
  },
)
```

**Comment by bweston92** [comment]
Happens when using the latest Docker rules.

**Comment by terinjokes** [comment]
About 6 months ago in https://github.com/bazelbuild/rules_docker/commit/1144f83122750fe4aca139bd0f205d99c9bd94c1, the Docker rules changed the arguments to `_get_layers`. Shortly thereafter, these rules were updated with the new parameter order in https://github.com/bazelbuild/rules_k8s/commit/e554f0c360c90d8b5edb55c8cb89afa9aa7b35bf.

In short, if you've updated the Docker rules, you need to update the k8s rules too.

**Comment by bweston92** [comment]
Thanks for getting letting me know @terinjokes  :)
