### ISSUE TITLE
Update use of org_pubref_rules_protobuf to fix issue with set constructor

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_k8s#41]
Since https://github.com/bazelbuild/bazel/commit/a6ad2d5564ad8ce7c7ebd0ba093db578cf5ae3cf, use of the `set` constructor instead of `depset` is an error.

https://github.com/pubref/rules_protobuf/releases has fixed this in their latest release. Please upgrade rules_k8s to the latest release or the next Bazel release will break your build.

Error message:
```
$ bazel-dev build //examples/hellogrpc/proto:all
...
ERROR: /usr/local/google/home/jcater/repos/rules_k8s/examples/hellogrpc/proto/BUILD:5:1: Traceback (most recent call last):
	File "/usr/local/google/home/jcater/repos/rules_k8s/examples/hellogrpc/proto/BUILD", line 5
		cc_proto_library(name = "cc", protos = ["simple.pro..."])
	File "/usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/5c3b0c3e069ecb95f72b7ff62a3e5298/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 97, in cc_proto_library
		native.cc_library(name = name, srcs = (srcs + [(name...")]), <2 more arguments>)
	File "/usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/5c3b0c3e069ecb95f72b7ff62a3e5298/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 100, in native.cc_library
		list(set(((deps + proto_deps) + compi...)))
	File "/usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/5c3b0c3e069ecb95f72b7ff62a3e5298/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 100, in list
		set(((deps + proto_deps) + compile_d...))
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
...
```

**Comment by mattmoor** [comment]
There is a PR for this waiting on @pcj: https://github.com/bazelbuild/rules_k8s/pull/40

**Comment by mattmoor** [comment]
Merged the PR.
