### ISSUE TITLE
error on upgrade to 0.2 

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_k8s#437]
This was working before the upgrade to `0.2`

```
ERROR: /home/f.wiles/workspace/WORKSPACE/apps/APPNAME/BUILD.bazel:3:1: in _k8s_object_delete rule //apps/APPNAME:deploy.staging.namespace.json.de
lete: 
Traceback (most recent call last):
        File "/home/f.wiles/workspace/WORKSPACE/apps/APPNAME/BUILD.bazel", line 3
                _k8s_object_delete(name = 'deploy.staging.namespace.json.delete')
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/io_bazel_rules_k8s/k8s/object.bzl", line 232, in _common_impl
                depset(transitive = kubectl_tool_info.t...)
expected value of type 'sequence of depsets or NoneType' for parameter 'transitive', for call to function depset(x = None, order = "default", direct = None, transitive = None, items = [])
ERROR: Analysis of target '//apps/APPNAME:deploy.staging.namespace.json.delete' failed; build aborted: Analysis of target '//apps/APPNAME:d
eploy.staging.namespace.json.delete' failed; build aborted
```

We define our kubectl binary as it states in the doc: https://github.com/bazelbuild/rules_k8s/tree/master/toolchains/kubectl#download-a-custom-kubectl-binary

Is there something else that needs to be updated so that `kubectl_tool_info.tool_target.files` has a value?
```
load("@io_bazel_rules_k8s//toolchains/kubectl:kubectl_configure.bzl", "kubectl_configure")

http_file(
    name = "k8s_binary",
    downloaded_file_path = "kubectl",
    executable = True,
    sha256 = "49f7e5791d7cd91009c728eb4dc1dbf9ee1ae6a881be6b970e631116065384c3",
    urls = ["https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl"],
)

kubectl_configure(
    name = "k8s_config",
    kubectl_path = "@k8s_binary//file",
)

load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories")
k8s_repositories()

load("@io_bazel_rules_k8s//k8s:k8s_go_deps.bzl", k8s_go_deps = "deps")
k8s_go_deps()
```

**Comment by smukherj1** [comment]
Hi @Toxicable, thanks for reporting. I created #441 to fix this.
